name: Publish Site
on:
  push:
    branches: [main]
    paths: ['_site/**']
  pull_request:
    branches: [main]
    paths: ['_site/**']
  workflow_dispatch:
jobs:
  quarto-site:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
        r: ['release']
        r-repo: ['https://cloud.r-project.org']
    # Only runs PR jobs concurrently & uses same group as other ghpages jobs
    # PR jobs run in their own branch & do not deploy anything - so we assume they can run concurrently
    concurrency:
      group: ghpages-${{ github.event_name != 'pull_request' || github.run_id }}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      RENV_CONFIG_REPOS_OVERRIDE: ${{ matrix.r-repo }}
    steps:
      - uses: actions/checkout@v3
      - name: Deploy site to GitHub pages 🚀
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: _site
          target-folder: .
